added usage and environment var for db
Clinical-Genomics/mwgs pull request #18
Opened 2018-04-23 08:51 UTC by patrikgrenfeldt

2018-10-30 08:36 UTC, ingkebil requested changes

2018-10-30 08:36 UTC, ingkebil commented on README.md
> +MWGS_SQL_DATABASE_URI 'SQLAlchemy database URI pointing to the database'
if this is a bash env var, it should be in the format of `KEY=value`

2018-10-30 08:36 UTC, ingkebil commented on README.md
> +$ mwgs start [path to sample dir]
```
$ mwgs start [path to sample dir]
```

2018-10-30 08:36 UTC, ingkebil commented on README.md
> +$ mwgs project [path to project dir]
```
$ mwgs project [path to project dir]
```

2018-10-30 08:36 UTC, ingkebil commented on README.md
> +$ mwgs add [path to stats file]
```
$ mwgs add [path to stats file]
```

2018-12-06 10:24 UTC, patrikgrenfeldt commented
@sylvinite do you have any idéa what this is about?

2018-12-11 07:06 UTC, patrikgrenfeldt commented
I'm closing this PR since I don't recollect creating it and no one else claimed it so far

2018-12-11 07:06 UTC, closed without merging